# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
